package com.nordicpeak.flowengine.queries.textfieldquery;

import java.io.Serializable;
import java.lang.reflect.Field;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.reflection.ReflectionUtils;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "text_field_query_instance_values")
@XMLElement
public class TextFieldValue extends GeneratedElementable implements Serializable {

	private static final long serialVersionUID = 6354162344651352603L;

	public static final Field TEXT_FIELD_RELATION = ReflectionUtils.getField(TextFieldValue.class, "textField");

	@DAOManaged(autoGenerated = true)
	@Key
	@XMLElement
	private Integer textFieldValueID;

	@DAOManaged(columnName = "queryInstanceID")
	@ManyToOne
	private TextFieldQueryInstance instance;

	@DAOManaged(columnName = "textFieldID")
	@ManyToOne
	@XMLElement
	private TextField textField;

	@DAOManaged
	@XMLElement
	private String value;

	public TextFieldValue() {};

	public TextFieldValue(TextField textField, String value) {

		super();
		this.textField = textField;
		this.value = value;
	}

	public Integer getTextFieldValueID() {

		return textFieldValueID;
	}

	public void setTextFieldValueID(Integer textFieldValueID) {

		this.textFieldValueID = textFieldValueID;
	}

	public TextFieldQueryInstance getInstance() {

		return instance;
	}

	public void setInstance(TextFieldQueryInstance instance) {

		this.instance = instance;
	}

	public TextField getTextField() {

		return textField;
	}

	public void setTextField(TextField textField) {

		this.textField = textField;
	}

	public String getValue() {

		return value;
	}

	public void setValue(String value) {

		this.value = value;
	}
}
