package com.nordicpeak.flowengine.queries.fileuploadquery;

import java.io.Serializable;

import org.apache.commons.fileupload.FileItem;
import org.w3c.dom.Document;
import org.w3c.dom.Element;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.io.BinarySizeFormater;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;
import se.unlogic.standardutils.xml.XMLUtils;

@Table(name = "file_upload_files")
@XMLElement
public class FileDescriptor extends GeneratedElementable implements Serializable{

	private static final long serialVersionUID = -2448574125308713542L;

	@XMLElement
	private Integer temporaryFileID;

	@DAOManaged(autoGenerated = true)
	@Key
	@XMLElement
	private Integer fileID;

	@DAOManaged
	@XMLElement
	private String name;

	@DAOManaged
	@XMLElement
	private Long size;

	@DAOManaged(columnName = "queryInstanceID")
	@ManyToOne
	private FileUploadQueryInstance queryInstance;

	private FileItem fileItem;

	public Integer getFileID() {

		return fileID;
	}

	public void setFileID(Integer fileID) {

		this.fileID = fileID;
	}

	public String getName() {

		return name;
	}

	public void setName(String name) {

		this.name = name;
	}

	public FileItem getFileItem() {

		return fileItem;
	}

	public void setFileItem(FileItem fileItem) {

		this.fileItem = fileItem;
	}

	@Override
	public String toString() {

		return this.name + " (fileID: " + fileID + ")";
	}

	public Long getSize() {

		return size;
	}

	public void setSize(Long size) {

		this.size = size;
	}

	@Override
	public Element toXML(Document doc) {

		Element fileElement = super.toXML(doc);

		XMLUtils.appendNewElement(doc, fileElement, "FormatedSize", BinarySizeFormater.getFormatedSize(size));

		return fileElement;
	}

	public FileUploadQueryInstance getQueryInstance() {

		return queryInstance;
	}

	public void setQueryInstance(FileUploadQueryInstance queryInstance) {

		this.queryInstance = queryInstance;
	}


	public Integer getTemporaryFileID() {

		return temporaryFileID;
	}


	public void setTemporaryFileID(Integer temporaryFileID) {

		this.temporaryFileID = temporaryFileID;
	}
}
