package com.nordicpeak.flowengine.beans;

import java.sql.Timestamp;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.Table;

@Table(name = "flowengine_aborted_flow_instances")
public class AbortedFlowInstance {

	@DAOManaged(autoGenerated = true)
	@Key
	private Integer abortID;

	@DAOManaged
	private Integer flowFamilyID;

	@DAOManaged
	private Integer flowID;

	@DAOManaged
	private Integer stepID;

	@DAOManaged
	private Timestamp added;

	public Integer getAbortID() {

		return abortID;
	}

	public void setAbortID(Integer abortID) {

		this.abortID = abortID;
	}

	public Integer getFlowFamilyID() {

		return flowFamilyID;
	}

	public void setFlowFamilyID(Integer flowFamilyID) {

		this.flowFamilyID = flowFamilyID;
	}

	public Integer getFlowID() {

		return flowID;
	}

	public void setFlowID(Integer flowID) {

		this.flowID = flowID;
	}

	public Integer getStepID() {

		return stepID;
	}

	public void setStepID(Integer stepID) {

		this.stepID = stepID;
	}

	public Timestamp getAdded() {

		return added;
	}

	public void setAdded(Timestamp added) {

		this.added = added;
	}
}
