package com.nordicpeak.flowengine.beans;

import java.sql.Blob;
import java.sql.Timestamp;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.io.BinarySizeFormater;
import se.unlogic.standardutils.string.StringUtils;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;
import se.unlogic.standardutils.xml.XMLUtils;

import com.nordicpeak.flowengine.interfaces.ImmutableAttachment;

public abstract class BaseAttachment extends GeneratedElementable implements ImmutableAttachment {

	@DAOManaged(autoGenerated = true)
	@Key
	@XMLElement
	protected Integer attachmentID;

	@DAOManaged
	@XMLElement
	private String filename;

	@DAOManaged
	@XMLElement
	private Long size;

	@DAOManaged
	@XMLElement
	private Timestamp added;

	@DAOManaged
	@XMLElement
	private Blob data;

	@Override
	public abstract BaseMessage getMessage();

	@Override
	public Integer getAttachmentID() {

		return attachmentID;
	}

	public void setAttachmentID(Integer attachmentID) {

		this.attachmentID = attachmentID;
	}

	@Override
	public String getFilename() {

		return filename;
	}

	public void setFilename(String filename) {

		this.filename = filename;
	}

	@Override
	public Long getSize() {

		return size;
	}

	public void setSize(Long size) {

		this.size = size;
	}

	@Override
	public Timestamp getAdded() {

		return added;
	}

	public void setAdded(Timestamp added) {

		this.added = added;
	}

	@Override
	public Blob getData() {

		return data;
	}

	public void setData(Blob data) {

		this.data = data;
	}
	
	@Override
	public Element toXML(Document doc) {

		Element attachmentElement = super.toXML(doc);

		XMLUtils.appendNewElement(doc, attachmentElement, "FormatedSize", BinarySizeFormater.getFormatedSize(size));

		return attachmentElement;
	}
	
	@Override
	public String toString() {
		
		return StringUtils.toLogFormat(filename, 50) + " (ID: " + attachmentID + ")";
	}
}
